instantlinux/docker-tools

images/mythtv-backend/Dockerfile
images/mythtv-backend/README.md
images/mythtv-backend/src/entrypoint.sh

Updated entrypoint.sh and Dockerfile to prevent apache from wanting port 80. Makes this usable on boxes with another webserver running.
Upgraded to Ubuntu 18.04 Bionic
Added additional usage information to the readme describing usage without using compose/kubernetes/etc.

Update mythtv-backend image to 18.04 bionic, move off port 80

---

images/dovecot/entrypoint-dovecot.sh

It's missing a "!" which causes podman to give this error:
> standard_init_linux.go:211: exec user process caused "exec format error"

fix dovecot shebang

---

images/mythtv-backend/Dockerfile

include libmyth-python in the mythtv-backend build so that metadata jobs work.  without it, looks like this
```
$ /usr/share/mythtv/metadata/Television/ttvdb.py -t
The modules tvdb_api.py (v2.0 or greater).
They should have been installed along with the MythTV python bindings.
Error:(No module named 'MythTV')
```

include libmyth-python in the mythtv-backend build

---

images/spamassassin/Dockerfile
images/spamassassin/entrypoint.sh

2 Changes in this PR:
* sa-update is complaining about missing gpg and runs only with `--no-gpg` (which is not really an option). `/usr/bin/gpgv` shipped with Debian doesn-t work as replacement.
* Run `sa-update` on container start to not have to wait the next cron cycle to get an inital copy

[images/spamassassin] Install missing gpg and run sa-update on container start

---

images/spamassassin/Dockerfile

DCC plugin is installed but not loaded (`loadplugin` is commented in v310.pre). 
Debian is not using DCC by default, since it's not open-source. But since we ar egoing through the hassle of installing it, we might also enable it.

[images/spamassassin] Enable DCC by default

---

images/nut-upsd/Dockerfile
images/nut-upsd/Dockerfile.arm32
images/nut-upsd/Dockerfile.arm64
images/nut-upsd/README.md
images/nut-upsd/entrypoint.sh

This allows configuring nut driver's sdorder parameter. This is mainly useful when set to -1 as nut will not issue shutdown order to the UPS in low battery condition.
The container can't shutdown the host system anyway without further tweaks so shutting down the UPS seems unnecessary especially when using UPS that reports Low Battery very early.

Add nut sdorder configuration 

---

images/samba-dc/entrypoint.sh

As written in https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller. The "REALM"-Property is
"Kerberos realm. The uppercase version of the AD DNS domain. For example: SAMDOM.EXAMPLE.COM."

Realm should be upper-case.

---

images/ddclient/entrypoint.sh

Currently the docker entrypoint for ddclient image has the server hardcoded.
With this commit we can successfully use the env variable to modify the destination server.
I tested it on a k8s cluster (installing it with helm), injecting the new entrypoint as a volume to replace the one existing in the image, but would like to share the solution for the repository.

Make destination server configurable on ddclient docker entrypoint

---

images/samba-dc/Dockerfile
images/samba-dc/entrypoint.sh
images/samba-dc/smb.conf.j2

This PR addresses issue #44 and enhances PR #96.
PR #96 introduces the DNS_FORWARDER variables but samba-dc doesn't actually use the jinja2 templating despite the .j2 file extension. This PR moves from using sed to j2cli for templating and completes support for DNS_FORWARDER.

samba-dc actually supports DNS_FORWARDER

---

.image-gitlab-ci.yml
images/git-dump/Dockerfile
images/git-pull/Dockerfile

To improve detection of published CVE vulnerabilities, I want a vulnerability-checking pipeline step for each docker image.
Add support for [trivy](https://trivy.dev/), one of the most comprehensive free solutions.

SYS-598 add trivy scan

---

README.md
ansible/roles/mythfrontend/defaults/main.yml
images/mythtv-backend/Dockerfile
images/mythtv-backend/README.md
images/mythtv-backend/docker-compose.yml
images/mythtv-backend/helm/values.yaml
services/mythtv-backend/docker-compose.yml

MythTV version 33.1 was released 5-Feb-2023. Upgrade the docker image (backend) and ansible playbook (frontend).

SYS-610 upgrade mythtv to version 33

---

ansible/requirements.txt
ansible/roles/docker_node/tasks/main.yml
ansible/roles/docker_node/templates/docker.service.conf.j2
ansible/roles/fileserver/tasks/main.yml
ansible/roles/kubernetes/tasks/main.yml
ansible/roles/monitoring_agent/tasks/main.yml
ansible/roles/mythfrontend/tasks/main.yml
ansible/roles/network/tasks/main.yml
ansible/roles/users/tasks/main.yml
ansible/roles/volumes/tasks/main.yml
images/python-builder/Dockerfile
images/python-builder/Pipfile
images/python-builder/Pipfile.lock
images/python-wsgi/Dockerfile
images/python-wsgi/Pipfile
images/python-wsgi/Pipfile.lock

As developer I want the python images and ansible playbooks free of known vulnerabilities. This PR updates the `python-builder` and `python-wsgi` image, and phases out use of the `include` directive under ansible (used for k8s node and mythtv frontend config).

SYS-576 ansible import_tasks in place of include; update python-builder

---

images/nut-upsd/Dockerfile

Fix the default healthcheck for nut-upsd image.
To address bug report from @Alarez777:
> The healthcheck does not work in the nut-upsd container when the NAME environment variable is changed. It seems that the problem is in docker-tools/images/nut-upsd/dockerfile in this line because the $NAME variable is not considered:
```
HEALTHCHECK CMD upsc ups@localhost:3493 2>&1|grep -q stale && exit 1 || true
```
Local test: built image, launched with `$NAME` unset, then with `$NAME` set to a non-default value.

Issue #119 - fix NAME parameter in nut-upsd

---

images/haproxy-keepalived/Dockerfile
images/haproxy-keepalived/docker-compose.yml
images/haproxy-keepalived/entrypoint.sh
images/haproxy-keepalived/helm/Chart.yaml

Catch the SIGTERM signal to shut down keepalived properly upon container termination.
To address bug report from @breezytm:
> keepalive is failing to remove the network from the master causing the load balancing to fail during a failover. I reached out to keepalived team and here's what they said is the root cause. https://github.com/acassen/keepalived/issues/2201#issuecomment-1251444660
Local test: built image, launched and invoked `docker stop keepalived_app_1`.

Issue #86 remove VIP upon stop - haproxy-keepalived

---

.github/PULL_REQUEST_TEMPLATE.md
images/haproxy-keepalived/Dockerfile

Define the `STOPSIGNAL` in haproxy-keepalived image.
Kubernetes must be told explicitly what signal to use; by default the stopsignal is `SIGUSR1` and it should be `SIGTERM`.
Local test: built image, launched under helm, then `helm delete haproxy-keepalived`. Can now see the log message `Received SIGTERM` prior to container shutdown. (Still not working fully, though - the VIP isn't getting torn down despite the script apparently reaching the correct function.)

Issue #86 set stopsignal in haproxy-keepalived image

---

images/haproxy-keepalived/entrypoint.sh

Add a 1-second delay to the graceful-stop function in haproxy-keepalived.
Apparently the container was shutting down so quickly under k8s that keepalived didn't have time to remove the VIP.
Local testing using `helm delete haproxy-keepalived`.

Issue #86 wait for termination in haproxy-keepalived

---

images/data-sync/helm/Chart.yaml
images/data-sync/helm/values.yaml
images/rsyslogd/Dockerfile
images/rsyslogd/rsyslog-rotate

Add a corrected logrotate config to rsyslog image, and adjust the data-sync helm chart to handle latest jira logs.
As noted by @pjacak, the alpine distro's rsyslog package invokes an incorrect logrotate command. Also, latest version of jira has a couple of new logs that interfere with `unison` in the data-sync image.
Local testing.

Issue #79 replace lograte script in rsyslogd; adjust data-sync

---

ansible/roles/fileserver/tasks/virtualbox.yml
k8s/helm/gitlab/Chart.yaml
k8s/helm/gitlab/templates/configmap.yaml
k8s/helm/gitlab/values.yaml

Housekeeping update:
* Gitlab helm chart now supports version `16.3.3`, which retired the `logging_level` setting for gitaly. (There is still 20x as much log output from gitlab container as there should be -- almost none of it useful -- and nobody at GitLab wants to tackle this problem after years of complaints.)
* Replaced deprecated `apt_key` resource with `get_url` in ansible fileserver role: I dunno why the folks at ansible didn't just fix apt_key to do the right thing for debian-based distros
Support latest versions to comply with current security best practices.
Brought up gitlab, verified functionality; cleared out virtualbox repo settings and confirmed the new resource definition works properly.

SYS-607 update gitlab helm chart to 16.3.3; tweak ansible for virtualbox

---

images/nut-upsd/Dockerfile
images/nut-upsd/README.md
images/nut-upsd/entrypoint.sh
images/nut-upsd/helm/Chart.yaml
images/nut-upsd/helm/values.yaml

Adds the `MAXAGE` parameter (default 15 seconds) for configuring upsd.conf, and change behavior of HEALTHCHECK under docker-compose (now kills container upon failure).
CyberPower UPS units have long had trouble with stale-data causing the container to fail, as noted in discussion of issue #67.

Issue #67 nut-upsd healthcheck improvements, add MAXAGE variable

---

images/postfix-python/Dockerfile
images/proftpd/Dockerfile
images/samba-dc/Dockerfile
images/weewx/Dockerfile

Dockerfile tweaks to enable builds of postfix-python proftpd samba-dc and weewx under alpine 3.19.
Package name changes etc.

SYS-617 breaking-change Dockerfile updates for alpine 3.19

---

images/dovecot/Dockerfile
images/dovecot/helm/Chart.yaml
images/haproxy-keepalived/Dockerfile
images/haproxy-keepalived/helm/Chart.yaml
images/mysqldump/helm/Chart.yaml
images/openldap/helm/Chart.yaml
images/samba-dc/Dockerfile
images/weewx/Dockerfile
k8s/helm/gitlab/Chart.yaml
k8s/helm/guacamole/Chart.yaml
k8s/helm/guacamole/subcharts/guacamole-server/Chart.yaml
k8s/helm/guacamole/subcharts/guacd/Chart.yaml
k8s/helm/splunk/Chart.yaml
lib/build/Makefile.docker_image

* Revert haproxy-keepalived and weewx
* Remove arm/v7 support for postfix-python because of weird problem with qemu on gitlab runner
* Add the --break-system-packages flag to make samba-dc's Dockerfile run pip (had to do this for other images)
* Upgrade charts of these third party images: gitlab, guacamole, splunk
New version of haproxy 2.9.x fails to run in my environment (100% CPU, takes down all services on all k8s workers after a short time, it's quite a sight to behold). The source repo for weewx is woefully outdated (no updates in 10 months) and I cannot find a way to make it run under alpine 3.19 without reverting py3-pillow somehow.
The other changes are routine security updates and housekeeping.
Lots of local testing.

SYS-619 roll back weewx / haproxy-keepalived; update a few helm charts

---

images/nut-upsd/Dockerfile

At times the application tries to use kill if it discovers a .pid (may be after a reboot) and the wall command, these two commands are available in util-linux
Error, command not found (kill and wall)
When starting the process, after a few minutes a wall command not found error appeared

add util-linux dependency

---

images/nut-upsd/Dockerfile

Publish the nut-upsd image version `2.8.2`. Alpine 3.19 has some recently published CVE vulnerabilities that aren't yet fixed in the  stock image.
The newest vulnerability corrections aren't available in the main repo, so this Dockerfile includes updates from edge repo.

Issue #149 security patch updates for nut-upsd

---

images/nagios/Dockerfile
images/nagios/entrypoint.sh

Upgrade the nagios image to `4.5.1-2.4.5` (from alpine edge repo).
Routine security-vulnerability maintenance.

SYS-622 nagios 4.5.1 image update

---

.image-gitlab-ci.yml
images/nagios/README.md

Bypass trivy vulnerability scan for all images. 
There are several new vulnerabilities in `alpine:3.19` base image, and no images based on it would build. This is a temporary "fix" to address other vulnerabilities in a few images prior to 3.20 coming out.
Local testing.

SYS-622 disable trivy scanner until alpine:3.20 arrives

---

.image-gitlab-ci.yml
images/postfix-python/requirements.txt
images/udp-nginx-proxy/Dockerfile
images/wxcam-upload/Dockerfile
images/wxcam-upload/helm/Chart.yaml

Bypass a few vulnerabilities to let builds continue on images postfix-python, udp-nginx-proxy, wxcam-upload.
Routine vulnerability patching.
Local testing and CI

SYS-622 trivy scan fixes - postfix-python, udp-nginx, wxcam-upload

---

.image-gitlab-ci.yml
images/weewx/Dockerfile

* Rearrange weewx `Dockerfile` to provide gcc build environment
* Bump trivy security scanner from 0.53.0 to 0.54.1
Initial 5.x upgrade didn't build on arm/v6 due to a wheel missing from published alpine python packages

SYS-623 fix and publish multi-platform weewx image

---

images/nut-upsd/Dockerfile
images/nut-upsd/README.md
images/nut-upsd/entrypoint.sh
images/nut-upsd/helm/Chart.yaml
k8s/Makefile.instances
k8s/Makefile.vars
k8s/Makefile.versions
k8s/README.md
k8s/install/ingress-nginx.yaml

Publish the nut-upsd image version `2.8.2-r2`, with correction to healthcheck script when handling `Stale` status from the devie driver.
Also made some doc updates: getting rid of more references to gitlab (local instance no longer supported by this repo), explained keycloak integration a bit more.
As reported in #171, the busybox `kill` command syntax was incorrect.

Issue #171 nut-upsd healthcheck

---

images/ddclient/entrypoint.sh
images/git-dump/Dockerfile
images/git-dump/entrypoint.sh

Fixes broken builds of ddclient and git-dump images.
The syntax of `chown` permitted a deprecated format _owner.group_ until alpine:3.21. Replace the dot with a colon wherever this appeared.

SYS-633 fix chown commands for ddclient / git-dump

---

images/mysqldump/mysql-backup.sh
images/nagios/Dockerfile
images/nagios/entrypoint.sh

Overrides the new default for mariadb-dump with `--skip-ssl`, fixes allgrants.sql dump, and eliminates deprecated names. (For historic reasons, still keeping the image name mysqldump even though it's been mariadb for years.) 
Updates nagios to 4.5.8.
Routine security updates.

SYS-633 mysqldump update for version 11.x, and nagios 4.5.8

---

ansible/roles/mythfrontend/defaults/main.yml
ansible/roles/mythfrontend/tasks/main.yml
ansible/roles/mythfrontend/tasks/vars/noble.yml
images/mysqldump/Dockerfile
images/mysqldump/README.md
images/mysqldump/entrypoint.sh
images/mysqldump/mysql-backup.sh
images/mythtv-backend/Dockerfile

Update mythtv-backend image to version 34.0. Clean out some of the deprecated opensuse support in mythfrontend ansible.
Rework the skip-ssl parameter in mysqldump (first added with PR #179).
Routine security and version updates.

SYS-633 update image and ansible for mythtv v34, and fix mysqldump image

---

ansible/Makefile
ansible/roles/docker_node/defaults/main.yml
ansible/roles/monitoring_agent/files/plugins/check_ethtool.pl
ansible/roles/monitoring_agent/files/plugins/check_ping.sh
ansible/roles/monitoring_agent/tasks/packages.yml
ansible/roles/network/defaults/main.yml
ansible/roles/network/tasks/netplan.yml
images/mysqldump/helm/values.yaml
images/mythtv-backend/helm/Chart.yaml
images/mythtv-backend/helm/values.yaml
images/nut-upsd/entrypoint.sh
images/weewx/helm/values.yaml
k8s/helm/guacamole/Chart.yaml
k8s/helm/restic/Chart.yaml
k8s/helm/restic/values.yaml
k8s/install/k8s-backup.yaml

This is a cleanup of minor issues since security-patching a month ago.
* ansible: Adjust default docker version 
* ansible: add check_ethtool nagios script
* ansible: adjust check_ping.sh to use grep instead of egrep (alpine 3.21)
* ansible: remove gateway4 reference from netplan (ubuntu 24.04)
* helm: expose skip-ssl param in mysqldump
* helm: mythtv-backend version
* helm: update subchart version dependencies in guacamole
* helm: restic version
* nut-upsd: remove debug statement in entrypoint
* k8s infra: use newer etcd for backup cron job
Routine update to handle deprecated syntax and versions under newest alpine and ubuntu.

SYS-636 housecleaning - ansible and helm

---

images/dhcpd-dns-pxe/helm/Chart.yaml
images/dhcpd-dns-pxe/helm/values.yaml
images/dovecot/helm/Chart.yaml
images/dovecot/helm/values.yaml
images/postfix-python/helm/Chart.yaml
images/postfix-python/helm/values.yaml
images/weewx/Dockerfile
images/weewx/README.md
images/weewx/entrypoint.sh
k8s/helm/etcd/Chart.yaml
k8s/helm/etcd/values.yaml

* Fix weewx entrypoint so it doesn't crash on startup if airlink host isn't specified
* Add podAntiAffinity to several helm charts so all pods and volumes are assigned to different k8s workers
The weewx image was broken since airlink was added.
There were several statefulsets that would come up improperly if count of available workers at initial startup was less than specified replica count.
CI and local testing

SYS-638 fix weewx startup, add antiAffinity to a few charts

---

images/proftpd/Dockerfile
images/proftpd/entrypoint.sh
images/proftpd/helm/Chart.yaml

Bump proftpd version to `1.3.8d-r0`, and remove DSA key generation.
As noted by @grosbedos:
> The proftpd image with sftp enabled no longer starts. I think openssh no longer supports DSA keys by default.

Issue #189 retire DSA keys from proftpd image

---

.image-gitlab-ci.yml
images/haproxy-keepalived/Dockerfile
images/spamassassin/Dockerfile
images/spamassassin/helm/values.yaml
images/udp-nginx-proxy/Dockerfile
lib/build/Makefile.docker_image

Update haproxy-keepalived, improve builds for spamassassin and udp-nginx-proxy
Vulnerability updates. The spamassassin image uses debian:bookworm, for which two CVEs were mitigated in a way that the trivy scanner doesn't respect. The nginx image likewise had a couple of CVEs which are mitigated in packages that came out after the tag `1.27.4-alpine` was built.
This is _not_ fully tested prior to merge: the change to .image-gitlab-ci.yml will trigger builds of all images, maxing out monthly minutes of gitlab executor quota (only want to do this once).

SYS-647 updates - haproxy-keepalived, spamassassin, udp-nginx-proxy

---

ansible/roles/monitoring_agent/files/plugins/check-file-exists
k8s/README.md
k8s/scripts/k8sudo

Adds a script `k8sudo` to k8s/scripts, which encrypts the key for admin.conf; also provides a nagios checker to avoid forgetting to invoke `k8lock`.
The admin.conf key is occasionally required for emergency work. There's not really any convenient way to store it with encryption-at-rest.
Manual testing.

SYS-648 k8sudo script to lock down k8s admin.conf

---

.image-gitlab-ci.yml
images/nagiosql/Dockerfile
images/nagiosql/README.md
images/nagiosql/entrypoint.sh
images/spamassassin/Dockerfile
images/spamassassin/helm/values.yaml

* nagiosql image updated from `3.5.0-4.4.13-r1` to `3.5.0-4.5.8-r0` under alpine:3.21
* libmilter added to spamassassin image
Routine security patching, and eliminate this error in the spamassassin build:
```
*** cannot build dccm without milter header and library ***
```

SYS-647 security update for nagiosql, add milter to spamassassin

---

images/proftpd/entrypoint.sh

Omit the DSA key from sftp.conf if `SFTP_ENABLE` is turned on.
The upstream packager hasn't yet gotten rid of the now fully-deprecated `ssh_host_dsa_key` from the distributed /etc/proftpd/conf.d/sftp.conf. The entrypoint script here blindly enabled the now-incorrect key.
Manual testing.

Issue #189 - adjust proftpd to omit DSA key

---

ansible/roles/mythfrontend/defaults/main.yml
images/mythtv-backend/Dockerfile
images/mythtv-backend/README.md
images/mythtv-backend/helm/Chart.yaml
images/mythtv-backend/helm/values.yaml
images/mythtv-backend/src/entrypoint.sh
images/rsyslogd/helm/values.yaml
k8s/scripts/k8sudo

* Upgrade mythtv-backend image: `35.0-fixes.202504212209.eaa307f0b6`
* Remove sshd, apache2 and mythtv-setup packages from mythtv-backend (deprecated since 34.0)
* Fix `k8sudo` monitoring (PR #196)
* Increase memory limit of rsyslogd to keep oom killer at bay
Routine security updates.

SYS-641 mythtv image updated to 35.0

---

ansible/roles/docker_node/defaults/main.yml
ansible/roles/kubernetes/defaults/main.yml
k8s/helm/gitea/values.yaml
k8s/helm/restic/values.yaml
k8s/install/monitor.yaml

Updates:
* k8s now `1.32.4`
* docker-ce now `28.1.1`
* cni now `1.6.0`
* gitea: helm chart had spurious `service` value
* restic: helm chart now restricted to smaller ephemeral limit
* monitor: yaml had incorrect port number
Routine patching and cleanup
Local testing.

SYS-651 kubernetes v1.32.4 and minor housekeeping

---

ansible/roles/volumes/handlers/main.yml
k8s/helm/grafana/Chart.yaml
k8s/helm/grafana/values.yaml
k8s/helm/restic/values.yaml

- Fix the ansible volume resize handler
- Remove superfluous redis subchart from grafana helm chart
- Remove superfluous ephemeral storage cap from resource limits of restic helm chart
Routine housekeeping
Local testing

SYS-652 miscellaneous fixes

---

images/dovecot/Dockerfile

When installing new version of dovecot, Dockerfile no longer needs to purge a directory under `/etc/ssl`.
Last update broke the build.

SYS-654 fix updated dovecot build

---

ansible/roles/mythfrontend/defaults/main.yml
ansible/roles/mythfrontend/tasks/drivers/intel.yml

When building a MythTV frontend with ansible, this removes the faulty Intel GPU driver for X11 (package name `xserver-xorg-video-intel`).
Support for those packages under Xorg has apparently been dropped, to the point that hardware acceleration no longer works if that package is present. This forces X11 initialization to properly recognize the `modesetting` driver which remains supported.
Local testing.

SYS-658 remove faulty intel GPU driver for mythtv frontend

---

k8s/helm/guacamole/subcharts/guacamole-server/values.yaml
k8s/helm/guacamole/values.yaml

Fixes for the Apache guacamole helm chart:
* Explicitly disable extensions `ban` and `ldap` by default
* Eliminate references to Authelia TOTP
* Enable the built-in TOTP
Version 1.6.0 added new defaults that break logins without additional configuration. LDAP needs additional configuration, so there's no point loading it without that configuration. The BAN extension also requires additional configuration when run behind a proxy, so it blocks all access whenever a brute-force attack happens (and such attacks continuously happen once the login URL becomes known to the hacker community). Authelia's TOTP is incompatible with login URLs that contain a `#` character, so to protect the system this PR adds TOTP by default. TOTP does not need additional configuration: if a user hasn't yet …

SYS-657 use built-in TOTP for guacamole, instead of Authelia

---

k8s/Makefile
k8s/Makefile.versions
k8s/install/ingress-nginx.yaml

Upgrades ingress-nginx to 1.13.1 and cert-manager to 1.16.1.
Routine security patching. See the [IngressNightmare](https://securitylabs.datadoghq.com/articles/ingress-nightmare-vulnerabilities-overview-and-remediation/) vulnerability report.
Local testing.

SYS-661 bump ingress-nginx from 1.11.2 to 1.13.1; cert-manager to 1.16.1

---

images/nut-upsd/Dockerfile
images/nut-upsd/README.md
images/nut-upsd/entrypoint.sh

Updates nut-upsd to version `2.8.3-r2` and adds a ULIMIT parameter with to set maximum open files (default 2048).
Under Debian trixie, an [issue #1672](https://github.com/networkupstools/nut/issues/1672) causes an out-of-memory error due to a high system default value for this parameter. Reported here as issue #213 by @Certain1989.
Local testing. Started a container and viewed the limits applied to upsd:
```
/ # ulimit -n
1048576
/ # echo $ULIMIT
2048
/ # ps aux
PID   USER     TIME  COMMAND
1 root      0:00 /usr/sbin/upsmon -D
22 root      0:00 /usr/lib/nut/usbhid-ups -a ups -u root
24 nut       0:00 /usr/sbin/upsd -u nut
25 nut       0:00 /usr/sbin/upsmon -D
46 root      0:00 sh
71 root      0:00 ps aux
/ # cat /proc/24/limits
Limit                     Soft Limit           Hard Limit …
```

Issue 213 nut trixie

---

k8s/Makefile
k8s/Makefile.vars
k8s/Makefile.versions
k8s/helm/grafana/Chart.yaml
k8s/helm/grafana/subcharts/prometheus/Chart.yaml
k8s/helm/grafana/subcharts/prometheus/values.yaml

Defines in the k8s `Makefile` the `nodelocaldns` import from kubernetes/kubernetes distribution repo. The sequence:
```
make imports/nodelocaldns.yaml
make imports/nodelocaldns
```
will add a daemonset and related services to add a DNS resolver at 169.254.0.10, and reconfigure kube-proxy to automatically redirect traffic 10.96.0.10 from all pods on all workers to the new address. 
A prometheus scraper for grafana is added here as well, to support [dashboard 11759](https://grafana.com/grafana/dashboards/11759-coredns-with-nodelocaldns/). And: bumped Prometheus version from 3.3.1 to 3.5.0.
UDP traffic between k8s nodes isn't reliable, especially under load. This is the widely-documented workaround to improve DNS reliability.
Local testing.

SYS-662 add node-local-dns cache from kubernetes distro

---

images/nut-upsd/entrypoint.sh

Without this line added, the API_USER account cannot do things like enable/disable the beeper
I added in a line to the entrypoint.sh that allows the API_USER to issue commands. This was the workaround fix I made on for my own uses. The sample uspd.users file mentions how `instcmds` works [here](https://networkupstools.org/docs/man/upsd.users.html)
This is needed in order to have Home Assistant do commands such as enable/disable the beeper.
Without this change, I got an access denied message when trying to run commands. I replaced the original entrypoint.sh with this change and created a new docker image on top of the instantlinux/nut-upsd and supplanted my new entrypoint.sh. I was able to issue commands after that.

Allow API_USER to have access to commands

---

README.md
images/nut-upsd/Dockerfile
images/nut-upsd/README.md
images/nut-upsd/entrypoint.sh
images/nut-upsd/helm/Chart.yaml
images/nut-upsd/helm/templates/app.yaml
images/nut-upsd/helm/values.yaml

This adds a bit of previously-unwanted complexity to the entrypoint startup script, risking bugginess down the road. But at request of multiple users, this PR defines these capabilities for the `nut-upsd` image and helm chart:
* Add support for ACTIONS, INSTCMDS and NOTIFYCMD variables
* Add support for a helm configmap to define a notify script under kubernetes
* Add `curl` package for use by scripts
* Clarify doc in the README to make troubleshooting easier / less necessary
As requested by @paolofaz, @474N, @dmcc, @markuswells in issues #108, #128, #206, #226.
Lots of local testing.

Issue #108 and issue #206 - nut-upsd enhancements
